language: java

sudo: false

jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - "mvn clean compile test -DVAULT_TOKEN=$VAULT_TOKEN"

after_success:
  - bash <(curl -s https://codecov.io/bash)